
# CREATE NEW USER
POST http://localhost:8080/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "name": "Tom Cruz",
  "email": "thompsonmanda08@gmail.com",
  "password": "Tm123456!"
  
}

###


# AUTHENTICATE USER
POST http://localhost:8080/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "email": "thompsonmanda08@gmail.com",
  "password": "Tm123456!"
}

###


# FETCH ALL USERS
GET http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NDc5NDcxMTYsImlhdCI6MTc0Nzg2MDcxNn0.-7gtfSrGMCrERQaqIF-mY7gfTgOt5Sgzs2JxUaOTD_s
###

